WHITELIST_COMMANDS = {
    "cd": ["cd keys",
           "cd keys/",
           "cd payments",
            "cd payments/",
           "cd users",
           "cd users/"],
    "ls": ["ls","ls -l","ls -a", "ls -R","ls -d", "ls -R","ls -r","ls -t","ls ../keys","ls ../payments","ls ../users"],
    "cat": ["cat keys/p_key.pkcs1",
            "cat users/user.txt",
            "cat payments/credit_cards.json",
            "cat psw.txt", 
            "cat credit_cards.json", 
            "cat p_key.pkcs1", 
            "cat user.txt"],
    "ifconfig":["ifconfig","ifconfig -a"],
    "id":["id","id -a"],
    "echo": ["echo"],
    "clear": ["clear"],
    "pwd": ["pwd"],
    "whoami": ["whoami"],
}