version: '3'
services:
  ssh_service:
      build:
        context: ./ssh
        dockerfile: Dockerfile
      environment:
        - SSH_REAL_PORT=${SSH_REAL_PORT}
        - SSH_REMOTE_PORT=${SSH_REMOTE_PORT}
        - IP_ELASTIC=${IP_ELASTIC}
      ports:
        - "${SSH_REMOTE_PORT}:${SSH_REAL_PORT}"
