version: '3'
services:
  modbus_service:
      build:
        context: ./modbus
        dockerfile: Dockerfile
      environment:
        - MODBUS_REAL_PORT=${MODBUS_REAL_PORT}
        - MODBUS_REMOTE_PORT=${MODBUS_REMOTE_PORT}
        - IP_ELASTIC=${IP_ELASTIC}
      ports:
        - "${MODBUS_REMOTE_PORT}:${MODBUS_REAL_PORT}"
